// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0lxJymbDhfx1QOXd4MiknbSiFCrU4tDs',
    appId: '1:889155684752:web:06187070ba358846f64b15',
    messagingSenderId: '889155684752',
    projectId: 'flutter-run--d-chrome-85811',
    authDomain: 'flutter-run--d-chrome-85811.firebaseapp.com',
    storageBucket: 'flutter-run--d-chrome-85811.firebasestorage.app',
    measurementId: 'G-2R97KLW7GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaAa3T1EWJwW_j5OnRZeydEmOG8I0x_0A',
    appId: '1:889155684752:android:f9ec4722e4354521f64b15',
    messagingSenderId: '889155684752',
    projectId: 'flutter-run--d-chrome-85811',
    storageBucket: 'flutter-run--d-chrome-85811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKpGP3elz48zW9D_-ymcHQqCS82KnwrvA',
    appId: '1:889155684752:ios:1e6aa150b29757faf64b15',
    messagingSenderId: '889155684752',
    projectId: 'flutter-run--d-chrome-85811',
    storageBucket: 'flutter-run--d-chrome-85811.firebasestorage.app',
    iosBundleId: 'com.example.backHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKpGP3elz48zW9D_-ymcHQqCS82KnwrvA',
    appId: '1:889155684752:ios:1e6aa150b29757faf64b15',
    messagingSenderId: '889155684752',
    projectId: 'flutter-run--d-chrome-85811',
    storageBucket: 'flutter-run--d-chrome-85811.firebasestorage.app',
    iosBundleId: 'com.example.backHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0lxJymbDhfx1QOXd4MiknbSiFCrU4tDs',
    appId: '1:889155684752:web:c8880c92f3cc7ea9f64b15',
    messagingSenderId: '889155684752',
    projectId: 'flutter-run--d-chrome-85811',
    authDomain: 'flutter-run--d-chrome-85811.firebaseapp.com',
    storageBucket: 'flutter-run--d-chrome-85811.firebasestorage.app',
    measurementId: 'G-R4WCNE1NRX',
  );

}